/* GENERATED by scripts/build_web.py from web-shared/src/dam-app.jsx — do not edit; edit the source and rebuild. source-sha256=c0bf60bc94fd26bed383fc42bea17315d3f97b834a1374ec9da42257130846c9 */
function ownKeys(e, r) { var t = Object.keys(e); if (Object.getOwnPropertySymbols) { var o = Object.getOwnPropertySymbols(e); r && (o = o.filter(function (r) { return Object.getOwnPropertyDescriptor(e, r).enumerable; })), t.push.apply(t, o); } return t; }
function _objectSpread(e) { for (var r = 1; r < arguments.length; r++) { var t = null != arguments[r] ? arguments[r] : {}; r % 2 ? ownKeys(Object(t), !0).forEach(function (r) { _defineProperty(e, r, t[r]); }) : Object.getOwnPropertyDescriptors ? Object.defineProperties(e, Object.getOwnPropertyDescriptors(t)) : ownKeys(Object(t)).forEach(function (r) { Object.defineProperty(e, r, Object.getOwnPropertyDescriptor(t, r)); }); } return e; }
function _defineProperty(e, r, t) { return (r = _toPropertyKey(r)) in e ? Object.defineProperty(e, r, { value: t, enumerable: !0, configurable: !0, writable: !0 }) : e[r] = t, e; }
function _toPropertyKey(t) { var i = _toPrimitive(t, "string"); return "symbol" == typeof i ? i : i + ""; }
function _toPrimitive(t, r) { if ("object" != typeof t || !t) return t; var e = t[Symbol.toPrimitive]; if (void 0 !== e) { var i = e.call(t, r || "default"); if ("object" != typeof i) return i; throw new TypeError("@@toPrimitive must return a primitive value."); } return ("string" === r ? String : Number)(t); }
/* dam-app.jsx — the QPF_dam/web (dam site) dashboard app (JSX source).
 * Compiled by scripts/build_web.py into QPF_dam/web/app.js;
 * after editing: run the build and bump ?v= on app.js in that index.html.
 * Runs after dashboard-core.js, which provides window.QPFShared. */
const {
  useState,
  useEffect,
  useMemo,
  useRef,
  useCallback
} = React;
const {
  MODEL_COLOR,
  FIELDS,
  FIELD_ORDER,
  j,
  dmy,
  dm,
  dow,
  hhmm,
  num,
  norm,
  binsFor,
  colorFor,
  winTiles,
  stepTiles,
  Timeline,
  OffGridNote,
  Credit,
  attachTcOverlay,
  TcBanner,
  escHtml
} = window.QPFShared;

/* ------------------------------------------------------------------ map */
function MapPane({
  legend,
  tmeta,
  admin,
  dams,
  model,
  field,
  frameIdx,
  markerValues,
  ver,
  onPick,
  focus,
  tc,
  onTcLead,
  tcSync
}) {
  const elRef = useRef(null),
    mapRef = useRef(null),
    rasterRef = useRef(null);
  const markersRef = useRef({}),
    selRef = useRef(null),
    boundRef = useRef(null);
  const bins = binsFor(field, legend);
  const idOf = useMemo(() => {
    const o = {};
    (markerValues?.ids || []).forEach((id, i) => o[id] = i);
    return o;
  }, [markerValues]);
  useEffect(() => {
    const map = L.map(elRef.current, {
      preferCanvas: true,
      zoomControl: false,
      minZoom: 4,
      maxZoom: 12
    }).setView([16.5, 105.5], 5);
    L.control.zoom({
      position: "topright"
    }).addTo(map);
    L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}", {
      attribution: "Tiles &copy; Esri",
      maxZoom: 16,
      maxNativeZoom: 16
    }).addTo(map);
    map.createPane("raster");
    map.getPane("raster").style.zIndex = 200;
    map.createPane("admin");
    map.getPane("admin").style.zIndex = 400;
    map.getPane("admin").style.pointerEvents = "none";
    map.createPane("bounds");
    map.getPane("bounds").style.zIndex = 350;
    map.createPane("labels");
    map.getPane("labels").style.zIndex = 655;
    map.getPane("labels").style.pointerEvents = "none";
    L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}", {
      maxZoom: 16,
      maxNativeZoom: 16,
      pane: "labels"
    }).addTo(map);
    // Vietnamese island groups, labelled prominently like a major city
    [[16.5, 112.0, "quần đảo Hoàng Sa<br>(Việt Nam)"], [9.7, 113.8, "quần đảo Trường Sa<br>(Việt Nam)"]].forEach(([la, lo, txt]) => L.marker([la, lo], {
      pane: "labels",
      interactive: false,
      icon: L.divIcon({
        className: "island-label",
        html: txt,
        iconSize: [150, 34],
        iconAnchor: [75, 17]
      })
    }).addTo(map));
    const applyZ = () => {
      const el = map.getContainer();
      el.classList.toggle("zlabels", map.getZoom() >= 9);
    };
    map.on("zoomend", applyZ);
    mapRef.current = map;
    return () => map.remove();
  }, []);

  // EXACT boundary vectors (province / neighbouring-country / Greater Mekong
  // basin) drawn with L.geoJSON on a non-interactive pane above the raster —
  // replaces the old basin.png image overlay, which could look geographically
  // shifted. Markers stay clickable (pane has pointer-events:none).
  const adminLayersRef = useRef([]);
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    adminLayersRef.current.forEach(l => map.removeLayer(l));
    adminLayersRef.current = [];
    const add = (gj, style) => {
      if (!gj) return;
      const l = L.geoJSON(gj, {
        pane: "admin",
        interactive: false,
        style: () => style
      }).addTo(map);
      adminLayersRef.current.push(l);
    };
    add(admin.basin, {
      color: "#5a6b7d",
      weight: 1.0,
      opacity: .55,
      fill: false
    });
    add(admin.adm1, {
      color: "#7a8896",
      weight: 0.8,
      opacity: .5,
      fill: false
    });
    add(admin.tinh, {
      color: "#44525f",
      weight: 1.0,
      opacity: .7,
      fill: false
    });
  }, [admin]);

  // one raster path for EVERY source (ensembles + VForce-cast): a pre-rendered
  // PNG per source/field/frame over that source's own bounds
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !tmeta) return;
    const M = tmeta.models[model];
    if (!M || !M.fields.includes(field)) {
      if (rasterRef.current) {
        map.removeLayer(rasterRef.current);
        rasterRef.current = null;
      }
      return;
    }
    const [s, w, n, e] = M.bounds;
    const b = [[s, w], [n, e]];
    const url = `tiles/${model}/${field}/${String(frameIdx).padStart(2, "0")}.png?v=${encodeURIComponent(ver)}`;
    if (!rasterRef.current) rasterRef.current = L.imageOverlay(url, b, {
      opacity: .74,
      pane: "raster",
      interactive: false
    }).addTo(map);else {
      rasterRef.current.setUrl(url);
      rasterRef.current.setBounds(b);
      if (!map.hasLayer(rasterRef.current)) rasterRef.current.addTo(map);
    }
  }, [tmeta, model, field, frameIdx, ver]);

  // markers, coloured from the small marker_values file (no grid on the client)
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !dams) return;
    if (!Object.keys(markersRef.current).length) {
      dams.features.forEach(f => {
        const [lon, lat] = f.geometry.coordinates;
        const mk = L.circleMarker([lat, lon], {
          radius: 5,
          weight: 1.2,
          color: "#2a3542",
          fillColor: "#bcd",
          fillOpacity: .9
        });
        mk.on("click", () => onPick(f.properties));
        mk.bindTooltip(escHtml(f.properties.name), {
          permanent: true,
          direction: "top",
          className: "dam-label",
          offset: [0, -6]
        });
        mk.addTo(map);
        markersRef.current[f.properties.id] = mk;
      });
    }
    const mv = markerValues ? markerValues.models[model]?.[field] : null;
    const row = mv ? mv[frameIdx] : null;
    dams.features.forEach(f => {
      const id = f.properties.id;
      const mk = markersRef.current[id];
      if (!mk) return;
      const di = idOf[id];
      const v = row && di != null ? row[di] : null;
      const col = colorFor(v, bins);
      mk.setStyle({
        fillColor: col || "#dfe6ee",
        fillOpacity: col ? .95 : .55,
        radius: 5
      });
    });
    if (selRef.current && markersRef.current[selRef.current]) markersRef.current[selRef.current].setStyle({
      radius: 8,
      weight: 2.4,
      color: "#12324d"
    }).bringToFront();
  }, [dams, tmeta, model, field, frameIdx, bins, onPick, markerValues, idOf]);

  // focus: highlight + zoom to the (coarse) marker position. No boundary
  // overlay and no per-dam data fetch any more — detail lives on the linked
  // standalone page.
  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    if (selRef.current && markersRef.current[selRef.current]) markersRef.current[selRef.current].setStyle({
      radius: 5,
      weight: 1.2,
      color: "#2a3542"
    });
    selRef.current = focus ? focus.id : null;
    if (boundRef.current) {
      map.removeLayer(boundRef.current);
      boundRef.current = null;
    }
    if (focus && markersRef.current[focus.id]) {
      const mk = markersRef.current[focus.id];
      mk.setStyle({
        radius: 8,
        weight: 2.4,
        color: "#12324d"
      }).bringToFront();
      // A search result always flies to and zooms in on the dam (even when the
      // map is already zoomed in on somewhere else); a marker click only nudges
      // the zoom up if the map is still far out.
      if (focus.zoom) map.flyTo(mk.getLatLng(), Math.max(map.getZoom(), 11), {
        duration: .6
      });else if (map.getZoom() < 9) map.setView(mk.getLatLng(), 9);
    }
  }, [focus]);

  // cyclone overlay (optional tc.json) — own panes, dam clicks keep working.
  // onLead (via a ref) lets the TC player drive the rainfall raster to the
  // same valid time.
  const onTcLeadRef = useRef(onTcLead);
  onTcLeadRef.current = onTcLead;
  const tcApiRef = useRef(null);
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !tc) return;
    const api = attachTcOverlay(map, tc, {
      onLead: (h, ms) => onTcLeadRef.current && onTcLeadRef.current(h, ms)
    });
    tcApiRef.current = api;
    return () => {
      tcApiRef.current = null;
      api();
    };
  }, [tc]);
  // reverse sync: the rain timeline (play or frame click) drives the
  // cyclone display to the same valid time
  useEffect(() => {
    if (tcSync && tcApiRef.current) tcApiRef.current.syncTo?.(tcSync.t, tcSync.gate);
  }, [tcSync]);
  return /*#__PURE__*/React.createElement("div", {
    id: "map",
    ref: elRef
  });
}

/* ------------------------------------------------------------- detail */
// Clicking a dam no longer opens an in-app drawer: every dam has a
// standalone, self-contained page (charts, warning summary, CSV downloads)
// built by process_dam_html.py --public and published under dams/. This
// small card opens it in a new tab or downloads the file.
function DamCard({
  dam,
  onClose,
  ver
}) {
  const file = dam.page ? dam.page.split("/").pop() : "";
  // Cache-bust the link: the detail page is a SELF-CONTAINED html with this
  // run's forecast baked in, so without a version the browser happily serves
  // the previous run's copy from cache.
  const pageHref = dam.page ? dam.page + "?v=" + encodeURIComponent(ver || "") : null;
  return /*#__PURE__*/React.createElement("aside", {
    className: "drawer",
    style: {
      width: 360
    }
  }, /*#__PURE__*/React.createElement("header", null, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h2", null, dam.name), dam.name_en && dam.name_en !== dam.name && /*#__PURE__*/React.createElement("div", {
    className: "en"
  }, dam.name_en), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, [dam.commune, dam.province].filter(Boolean).join(" · "))), /*#__PURE__*/React.createElement("button", {
    className: "xbtn",
    onClick: onClose,
    "aria-label": "\u0110\xF3ng"
  }, "\xD7")), /*#__PURE__*/React.createElement("div", {
    className: "body"
  }, dam.page ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      fontSize: 12.5,
      marginTop: 0
    }
  }, "Trang chi ti\u1EBFt c\u1EE7a h\u1ED3/\u0111\u1EADp n\xE0y g\u1ED3m: t\xF3m t\u1EAFt c\u1EA3nh b\xE1o, b\u1EA3n \u0111\u1ED3 ranh gi\u1EDBi & tr\u01B0\u1EDDng m\u01B0a theo \xF4 l\u01B0\u1EDBi, chu\u1ED7i th\u1EDDi gian theo v\xF9ng, x\xE1c su\u1EA5t m\u01B0a l\u1EDBn, bi\u1EC3u \u0111\u1ED3 h\u1ED9p v\xE0 t\u1EA3i CSV. Trang l\xE0 m\u1ED9t t\u1EC7p HTML t\u1EF1 ch\u1EE9a \u2014 t\u1EA3i v\u1EC1 v\u1EABn m\u1EDF \u0111\u01B0\u1EE3c kh\xF4ng c\u1EA7n m\u1EA1ng."), /*#__PURE__*/React.createElement("a", {
    className: "csvbtn",
    style: {
      display: "inline-block",
      textDecoration: "none",
      marginRight: 8
    },
    href: pageHref,
    target: "_blank",
    rel: "noopener"
  }, "M\u1EDF trang chi ti\u1EBFt \u2197"), /*#__PURE__*/React.createElement("a", {
    className: "csvbtn",
    style: {
      display: "inline-block",
      textDecoration: "none",
      background: "#2a3542"
    },
    href: pageHref,
    download: file
  }, "\u2913 T\u1EA3i v\u1EC1 (HTML)")) : /*#__PURE__*/React.createElement("p", {
    className: "hint"
  }, "Ch\u01B0a c\xF3 trang chi ti\u1EBFt cho h\u1ED3/\u0111\u1EADp n\xE0y.")));
}

/* --------------------------------------------------------------- panels */
function Search({
  dams,
  onPick
}) {
  const [q, setQ] = useState("");
  const hits = useMemo(() => {
    const t = norm(q.trim());
    if (t.length < 2) return [];
    return dams.features.filter(f => norm(f.properties.name).includes(t) || norm(f.properties.name_en).includes(t)).slice(0, 40);
  }, [q, dams]);
  return /*#__PURE__*/React.createElement("div", {
    className: "card searchbox"
  }, /*#__PURE__*/React.createElement("input", {
    value: q,
    onChange: e => setQ(e.target.value),
    placeholder: "T\xECm t\xEAn h\u1ED3 / \u0111\u1EADp\u2026"
  }), hits.length > 0 && /*#__PURE__*/React.createElement("div", {
    className: "card results"
  }, hits.map(f => /*#__PURE__*/React.createElement("button", {
    key: f.properties.id,
    onClick: () => {
      setQ("");
      onPick(f.properties, {
        zoom: true
      });
    }
  }, /*#__PURE__*/React.createElement("div", null, f.properties.name), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, [f.properties.province, f.properties.country].filter(Boolean).join(" · "))))));
}
function Legend({
  legend,
  model,
  field,
  tile
}) {
  const isVf = model === "vforce";
  const bins = binsFor(field, legend);
  const pref = isVf ? "VForce-cast — " : "";
  return /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "title",
    style: {
      marginBottom: 2
    }
  }, FIELDS[field].label), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 0,
      marginBottom: 6
    }
  }, pref + (field === "int" ? "cường độ mưa (mm/giờ) — kịch bản điển hình Q50 (ô lưới thô)" : field === "cum" ? "mưa cộng dồn từ giờ phát tin — kịch bản điển hình Q50 (ô lưới thô)" : field === "x50" ? "khả năng mưa vượt 50 mm/24 giờ" : field === "q90" ? "tổng mưa 24 giờ — kịch bản cực đoan (ô lưới thô)" : "tổng mưa 24 giờ — kịch bản điển hình (ô lưới thô)"), tile ? ` · ${tile}` : ""), bins.map((b, i) => /*#__PURE__*/React.createElement("div", {
    className: "legend-row",
    key: i
  }, /*#__PURE__*/React.createElement("span", {
    className: "swatch",
    style: {
      background: b.color
    }
  }), /*#__PURE__*/React.createElement("span", null, b.label))), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 6
    }
  }, "Ch\u1EA5m tr\xF2n = h\u1ED3/\u0111\u1EADp, t\xF4 m\xE0u theo ngu\u1ED3n \u0111ang ch\u1ECDn."));
}
function Bulletin({
  bulletin,
  meta
}) {
  const [open, setOpen] = useState(false);
  const long = bulletin.text.length > 180;
  const short = long ? bulletin.text.slice(0, 165).replace(/\s\S*$/, "") + " …" : bulletin.text;
  return /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "title"
  }, "Nh\u1EADn \u0111\u1ECBnh b\u1EA3n tin"), /*#__PURE__*/React.createElement("div", {
    className: "bulletin"
  }, open || !long ? bulletin.text : short), long && /*#__PURE__*/React.createElement("button", {
    className: "btn-link",
    style: {
      marginTop: 6
    },
    onClick: () => setOpen(!open)
  }, open ? "Thu gọn" : "Xem đầy đủ"), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, "Ph\xE1t tin ", hhmm(meta.issued_ict || meta.init_ict), " ICT ", dmy((meta.issued_ict || meta.init_ict).slice(0, 10)), bulletin.source === "gemini" ? " · Nhận định tự động bởi AI Gemini" : " · Nhận định tự động từ dữ liệu khí tượng"));
}
/* ------------------------------------------------------------------ app */
function App() {
  const [meta, setMeta] = useState(null),
    [tmeta, setTmeta] = useState(null);
  const [dams, setDams] = useState(null),
    [markerValues, setMarkerValues] = useState(null);
  const [model, setModel] = useState("ensemble"),
    [field, setField] = useState("q50"),
    [idx, setIdx] = useState(0);
  // Phones: the panel covers the map, so start it collapsed there. Collapse
  // only when the viewport is KNOWN to be narrow — innerWidth can report 0
  // (hidden/not-yet-composited frame), and treating that as a phone would
  // start every desktop visit collapsed.
  const [panelOpen, setPanelOpen] = useState(() => {
    const w = typeof window === "undefined" ? 0 : window.innerWidth;
    return !(w > 0 && w <= 720);
  });
  const [playing, setPlaying] = useState(false),
    [focus, setFocus] = useState(null);
  const [bulletin, setBulletin] = useState(null),
    [admin, setAdmin] = useState({});
  const [tc, setTc] = useState(null);
  useEffect(() => {
    (async () => {
      const m = await j("latest.json?t=" + Date.now());
      const v = "?v=" + encodeURIComponent(m.created_utc);
      const [tm, d, mv] = await Promise.all([j("tiles/meta.json" + v), j("data/dams.geojson" + v), j("data/marker_values.json" + v)]);
      setMeta(m);
      setTmeta(tm);
      setDams(d);
      setMarkerValues(mv);
      fetch("bulletin.json" + v).then(r => r.ok ? r.json() : null).then(b => b && setBulletin(b)).catch(() => {});
      // active-cyclone tracks (process_tc.py) — optional, quiet season = absent
      fetch("tc.json" + v).then(r => r.ok ? r.json() : null).then(t => t && setTc(t)).catch(() => {});
      // exact boundary vectors (province / neighbouring-country / basin) — drawn
      // with L.geoJSON so they sit at true coordinates (the old basin.png raster
      // could look shifted)
      const A = m.admin || {};
      ["basin", "adm1", "tinh"].forEach(k => A[k] && j(A[k] + v).then(g => setAdmin(p => _objectSpread(_objectSpread({}, p), {}, {
        [k]: g
      }))).catch(() => {}));
    })().catch(e => {
      document.getElementById("root").innerHTML = '<div class="loading">Lỗi tải dữ liệu: ' + e.message + '</div>';
    });
  }, []);
  const tiles = useMemo(() => {
    if (!meta || !tmeta) return [];
    const M = tmeta.models[model];
    if (!M) return [];
    // 24-h windows: the SELECTED source's own axis. Steps: lead from the SAME
    // per-model anchor the windows use (M.anchor_ict = the issue snapped to
    // this model's step cadence) so a 6-hourly model reads +6/+12/... in line
    // with its +24/+48 windows, never the odd +3/+9/... a 3-hourly issue
    // produces. Fallbacks cover pre-update tiles files. Shared with dubaomua.
    if (FIELDS[field].kind === "win") return winTiles(M.windows);
    return stepTiles(M.steps, M.anchor_ict || tmeta.issued_ict || meta.issued_ict || meta.init_ict);
  }, [meta, tmeta, model, field]);
  useEffect(() => {
    if (idx >= tiles.length) setIdx(0);
  }, [tiles.length]);
  useEffect(() => {
    if (!playing || !tiles.length) return;
    const t = setInterval(() => setIdx(i => (i + 1) % tiles.length), 900);
    return () => clearInterval(t);
  }, [playing, tiles.length]);

  // The TC player aligns WHATEVER the user is looking at to the cyclone's
  // valid time: it never changes the source / field, only the frame index
  // on the current selection's own time axis.
  const tileTimes = useMemo(() => {
    if (!tmeta) return [];
    const M = tmeta.models[model];
    if (!M) return [];
    if (FIELDS[field].kind === "win") return (M.windows || []).map(w => Date.parse(w.end));
    return (M.steps || []).map(s => Date.parse(s));
  }, [tmeta, model, field]);
  // Who moved first decides the coupling: TC player first (no rain control
  // touched yet) -> default to Tổ hợp per-step intensity; rain side driven
  // by the user -> the TC player only aligns the frame on THEIR selection.
  const rainTouched = useRef(false);
  const tcLead = useCallback((h, validMs) => {
    if (!rainTouched.current && tmeta) {
      // Companion view when the cyclone player leads: VForce-cast per-step
      // intensity (radar-anchored, highest resolution), falling back to Tổ
      // hợp only when VForce-cast has no cycle this run.
      const prefer = (tmeta.models["vforce"] || {}).fields?.includes("int") ? "vforce" : "ensemble";
      const M = tmeta.models[prefer];
      if (M && M.fields.includes("int")) {
        setModel(prefer);
        setField("int");
        const steps = M.steps || [];
        let si = -1,
          sd = Infinity;
        steps.forEach((s, i) => {
          const d = Math.abs(Date.parse(s) - validMs);
          if (d < sd) {
            sd = d;
            si = i;
          }
        });
        if (si >= 0 && sd <= 3 * 3600e3 + 6e4) setIdx(si);
        return;
      }
    }
    let bi = -1,
      bd = Infinity;
    tileTimes.forEach((t, i) => {
      const d = Math.abs(t - validMs);
      if (d < bd) {
        bd = d;
        bi = i;
      }
    });
    // only move when the cyclone time actually falls on this axis (within
    // half the axis spacing) — beyond it, keep the user's frame
    const sp = tileTimes.length > 1 ? tileTimes[1] - tileTimes[0] : 24 * 3600e3;
    if (bi >= 0 && bd <= sp / 2 + 6e4) setIdx(bi);
  }, [tileTimes, tmeta]);
  // current frame's valid time (+gate): pushed into the cyclone overlay so
  // its display follows the rain timeline (reverse of tcLead)
  const tcSync = useMemo(() => {
    const t = tileTimes[idx];
    if (!t) return null;
    const sp = tileTimes.length > 1 ? tileTimes[1] - tileTimes[0] : 24 * 3600e3;
    return {
      t,
      gate: sp / 2 + 6e4
    };
  }, [tileTimes, idx]);

  // switching source keeps a valid field (fields per source from tiles/meta.json)
  const selModel = mid => {
    rainTouched.current = true;
    setModel(mid);
    setIdx(0);
    const fs = tmeta.models[mid].fields;
    if (!fs.includes(field)) setField(fs.includes("q50") ? "q50" : fs[0]);
  };

  // Clicking a dam only highlights it and opens the link card — the detail
  // lives on the dam's standalone page under dams/ (no per-dam fetch here).
  // `zoom` is set from the search box so the map flies to the chosen dam;
  // a bare marker click leaves the current view. The timestamp makes every
  // pick a new object so re-selecting the same dam still re-triggers the fly.
  const pick = useCallback((props, opts) => {
    setFocus({
      id: props.id,
      zoom: !!(opts && opts.zoom),
      _t: Date.now()
    });
  }, []);
  if (!meta || !tmeta || !dams) return /*#__PURE__*/React.createElement("div", {
    className: "loading"
  }, "\u0110ang t\u1EA3i d\u1EEF li\u1EC7u d\u1EF1 b\xE1o\u2026");
  const damProps = focus ? (dams.features.find(f => f.properties.id === focus.id) || {}).properties : null;
  const tile = tiles[idx] ? `${tiles[idx].top} · ${tiles[idx].bot}` : "";
  const avail = tmeta.models[model].fields;
  const fieldSet = FIELD_ORDER.filter(k => avail.includes(k)).map(k => FIELDS[k]);
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement(MapPane, {
    legend: meta.legend,
    tmeta: tmeta,
    admin: admin,
    dams: dams,
    model: model,
    field: field,
    frameIdx: idx,
    markerValues: markerValues,
    ver: meta.created_utc,
    onPick: pick,
    focus: focus,
    tc: tc,
    onTcLead: tcLead,
    tcSync: tcSync
  }), /*#__PURE__*/React.createElement("div", {
    className: "float topleft" + (panelOpen ? "" : " collapsed")
  }, /*#__PURE__*/React.createElement("div", {
    className: "stack" + (panelOpen ? "" : " collapsed")
  }, /*#__PURE__*/React.createElement("div", {
    className: "card brand"
  }, /*#__PURE__*/React.createElement("button", {
    className: "ptoggle",
    onClick: () => setPanelOpen(o => !o),
    "aria-expanded": panelOpen,
    title: panelOpen ? "Thu gọn bảng điều khiển" : "Mở bảng điều khiển",
    "aria-label": panelOpen ? "Thu gọn bảng điều khiển" : "Mở bảng điều khiển"
  }, panelOpen ? "\u2715" : "\u2630"), /*#__PURE__*/React.createElement("h1", null, "D\u1EF1 b\xE1o m\u01B0a t\u1ED5 h\u1EE3p \u0111\u1EBFn h\u1ED3 \u0111\u1EADp"), /*#__PURE__*/React.createElement("div", {
    className: "sub"
  }, "Vi\u1EC7t Nam \xB7 ph\xE1t tin", " ", hhmm(meta.issued_ict || meta.init_ict), " ICT ", dmy((meta.issued_ict || meta.init_ict).slice(0, 10)), " ", "\xB7 b\u1EA5m v\xE0o h\u1ED3/\u0111\u1EADp \u0111\u1EC3 m\u1EDF trang chi ti\u1EBFt"), /*#__PURE__*/React.createElement("div", {
    className: "sub",
    style: {
      marginTop: 2,
      opacity: .75
    }
  }, "Chu kỳ mô hình: ", meta.models.filter(m => m.init_ict || m.issue_ict).map(m => `${m.short_vi} ${hhmm(m.init_ict || m.issue_ict)} ${dm(m.init_ict || m.issue_ict)}`).join(" · "))), /*#__PURE__*/React.createElement(TcBanner, {
    tc: tc
  }), /*#__PURE__*/React.createElement(Search, {
    dams: dams,
    onPick: pick
  }), /*#__PURE__*/React.createElement("div", {
    className: "card pad",
    style: {
      paddingTop: 8,
      paddingBottom: 8
    }
  }, /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      margin: 0
    }
  }, "Bản đồ ưu tiên: ", /*#__PURE__*/React.createElement("a", {
    href: "dams/overview.html?v=" + encodeURIComponent(meta.created_utc),
    target: "_blank",
    rel: "noopener"
  }, "hồ đập toàn quốc ↗"))), /*#__PURE__*/React.createElement("div", {
    className: "card pad"
  }, /*#__PURE__*/React.createElement("p", {
    className: "lbl"
  }, "M\xF4 h\xECnh d\u1EF1 b\xE1o"), /*#__PURE__*/React.createElement("div", {
    className: "seg mdl",
    style: {
      "--mc": MODEL_COLOR[model]
    }
  }, meta.models.map(m => /*#__PURE__*/React.createElement("button", {
    key: m.id,
    className: model === m.id ? "on" : "",
    style: model === m.id ? {
      "--mc": MODEL_COLOR[m.id],
      "--mct": m.id === "ensemble" ? "#3d3000" : "#fff"
    } : {},
    onClick: () => selModel(m.id)
  }, m.short_vi))), /*#__PURE__*/React.createElement("p", {
    className: "lbl",
    style: {
      marginTop: 12
    }
  }, "Th\xF4ng tin hi\u1EC3n th\u1ECB"), /*#__PURE__*/React.createElement("div", {
    className: "seg"
  }, fieldSet.map(f => /*#__PURE__*/React.createElement("button", {
    key: f.key,
    className: field === f.key ? "on" : "",
    onClick: () => {
      rainTouched.current = true;
      setField(f.key);
      setIdx(0);
    }
  }, f.label))), /*#__PURE__*/React.createElement("p", {
    className: "hint",
    style: {
      marginTop: 8
    }
  }, meta.note), /*#__PURE__*/React.createElement(OffGridNote, {
    models: meta.models,
    model: model
  })), /*#__PURE__*/React.createElement(Legend, {
    legend: meta.legend,
    model: model,
    field: field,
    tile: tile
  }), bulletin && /*#__PURE__*/React.createElement(Bulletin, {
    bulletin: bulletin,
    meta: meta
  }), /*#__PURE__*/React.createElement(Credit, null))), /*#__PURE__*/React.createElement(Timeline, {
    tiles: tiles,
    idx: idx,
    playing: playing,
    setIdx: i => {
      rainTouched.current = true;
      setIdx(i);
    },
    setPlaying: p => {
      rainTouched.current = true;
      setPlaying(p);
    }
  }), damProps && /*#__PURE__*/React.createElement(DamCard, {
    dam: damProps,
    ver: meta.created_utc,
    onClose: () => setFocus(null)
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(App, null));
